# Generated by Django 5.1.1 on 2025-02-18 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0006_alter_registration_event_alter_registration_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='registration',
            name='is_checked_in',
            field=models.BooleanField(default=False),
        ),
    ]
