# Generated by Django 5.1.1 on 2025-02-23 02:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0007_registration_is_checked_in'),
    ]

    operations = [
        migrations.AddField(
            model_name='registration',
            name='check_in_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
