# Generated by Django 5.1.1 on 2025-02-25 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0008_registration_check_in_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='registration',
            name='check_out_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='registration',
            name='is_checked_out',
            field=models.BooleanField(default=False),
        ),
    ]
