# Generated by Django 5.1.1 on 2024-10-19 12:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='response',
            name='question',
        ),
        migrations.RemoveField(
            model_name='registration',
            name='event',
        ),
        migrations.RemoveField(
            model_name='registration',
            name='user',
        ),
        migrations.RemoveField(
            model_name='response',
            name='registration',
        ),
        migrations.DeleteModel(
            name='Attendance',
        ),
        migrations.DeleteModel(
            name='Question',
        ),
        migrations.DeleteModel(
            name='Registration',
        ),
        migrations.DeleteModel(
            name='Response',
        ),
    ]
