# Generated by Django 5.1.1 on 2025-02-18 19:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0008_alter_check_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Registration',
        ),
    ]
