# Generated by Django 5.1.1 on 2025-02-18 21:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0007_registration_is_checked_in'),
        ('feedback', '0009_delete_registration'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='check',
            name='is_checked_in',
        ),
        migrations.AddField(
            model_name='check',
            name='registration',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='events.registration'),
            preserve_default=False,
        ),
    ]
