# Generated by Django 5.1.1 on 2025-02-23 02:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0008_registration_check_in_time'),
        ('feedback', '0010_remove_check_is_checked_in_check_registration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='check',
            name='registration',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='events.registration'),
        ),
    ]
