# Generated by Django 5.1.1 on 2025-02-23 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0011_alter_check_registration'),
    ]

    operations = [
        migrations.AddField(
            model_name='check',
            name='check_in_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
