# Generated by Django 5.1.1 on 2025-02-25 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0012_check_check_in_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='check',
            name='check_out_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
