# Generated by Django 5.1.1 on 2024-11-15 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='qr_code',
            field=models.ImageField(blank=True, null=True, upload_to='qr_codes/'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='birthday',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='department',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='phone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
    from django.db import migrations, models

def add_default_qr_code(apps, schema_editor):
    UserProfile = apps.get_model('member', 'UserProfile')
    for profile in UserProfile.objects.all():
        profile.qr_code = "default_qr_code"
        profile.save()

class Migration(migrations.Migration):
    dependencies = [
        ('member', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='qr_code',
            field=models.CharField(max_length=255, blank=True, null=True),
        ),
        migrations.RunPython(add_default_qr_code),  # 添加這一行
    ]

