# Generated by Django 5.1.1 on 2024-12-04 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0003_alter_userprofile_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='qr_code',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='qr_data',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
