# Generated by Django 5.1.1 on 2024-12-04 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0006_alter_userprofile_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='phone',
            field=models.CharField(blank=True, default='N/A', max_length=20, null=True),
        ),
    ]
