# Generated by Django 5.1.1 on 2024-12-09 16:39

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0008_alter_userprofile_department_event'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='participants',
            field=models.ManyToManyField(related_name='member_checked_in_events', to=settings.AUTH_USER_MODEL),
        ),
    ]
