# Generated by Django 5.0.6 on 2025-02-09 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0009_alter_event_participants'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='phone',
            field=models.CharField(blank=True, default='N/A', max_length=10, null=True, unique=True),
        ),
    ]
